# Generated by Django 5.1.3 on 2024-12-02 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='dislikes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lesson',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
