# Generated by Django 5.1.3 on 2024-12-02 08:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dars', '0002_lesson_dislikes_lesson_likes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='student',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='liked',
            field=models.CharField(blank=True, choices=[('like', 'Like'), ('dislike', 'Dislike')], max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='experience',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(35)]),
        ),
    ]
